repos:
-   repo: https://github.com/igrr/astyle_py.git
    rev: v1.0.5
    hooks:
    -   id: astyle_py
        files: \.(c|h|cpp|hpp)$
        args:
          - --style=otbs
          - --attach-namespaces
          - --attach-classes
          - --indent=spaces=4
          - --convert-tabs
          - --align-pointer=name
          - --align-reference=name
          - --keep-one-line-statements
          - --pad-header
          - --pad-oper

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
        types_or: [c, c++]
    -   id: end-of-file-fixer
        types_or: [c, c++]
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        types_or: [c, c++]
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character

- repo: https://github.com/espressif/check-copyright/
  rev: v1.1.1
  hooks:
    - id: check-copyright
      args: ['--config', 'check_copyright_config.yaml']

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
    - id: codespell
      args: [--config=.codespellrc]